package com.playtomic.tests.wallet.framework.infrastructure.queries;

public final class WalletQueries {

  private WalletQueries() {}

  public static final String SELECT_WALLET =
      "SELECT WALLET_ID, BALANCE_VALUE, BALANCE_CURRENCY, CREATED_AT, UPDATED_AT FROM WALLET "
          + "WHERE WALLET_ID = :WALLET_ID";

  public static final String UPDATE_WALLET =
      "UPDATE WALLET SET BALANCE_VALUE = :BALANCE_VALUE, UPDATED_AT = :UPDATED_AT "
          + "WHERE WALLET_ID = :WALLET_ID AND UPDATED_AT = :OLD_UPDATED_AT";

  public static final String SELECT_TRANSACTIONS =
      "SELECT t.TRANSACTION_ID, t.CREATED_AT, t.UPDATED_AT, t.WALLET_ID, t.COMPLETED_ON, t.AMOUNT_VALUE, "
          + "t.AMOUNT_CURRENCY, o.NAME FROM TRANSACTIONS t "
          + "INNER JOIN OPERATION o ON o.OPERATION_ID = t.OPERATION_ID "
          + "INNER JOIN WALLET w ON w.WALLET_ID = t.WALLET_ID "
          + "WHERE w.WALLET_ID = :WALLET_ID";

  public static final String DELETE_TRANSACTIONS =
      "DELETE FROM TRANSACTIONS WHERE WALLET_ID = :WALLET_ID";

  public static final String ADD_TRANSACTION =
      "INSERT INTO TRANSACTIONS (TRANSACTION_ID, CREATED_AT, UPDATED_AT, WALLET_ID, OPERATION_ID, COMPLETED_ON, AMOUNT_VALUE, AMOUNT_CURRENCY)"
          + "VALUES (:TRANSACTION_ID, :CREATED_AT, :UPDATED_AT, :WALLET_ID, :OPERATION_ID, :COMPLETED_ON, :AMOUNT_VALUE, :AMOUNT_CURRENCY)";

  public static final String SELECT_OPERATION_ID =
      "SELECT OPERATION_ID FROM OPERATION WHERE NAME = :NAME";
}
