-- Create OPERATIONS table
CREATE TABLE OPERATION(
    OPERATION_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) COMMENT 'Unique operation identifier',
    NAME VARCHAR(254) NOT NULL COMMENT 'Operation type',
    PRIMARY KEY(OPERATION_ID)
);