-- Create TRANSACTIONS table
CREATE TABLE TRANSACTIONS(
    TRANSACTION_ID VARCHAR(254) NOT NULL COMMENT 'Unique transaction identifier',
    CREATED_AT TIMESTAMP NOT NULL COMMENT 'Created date',
    UPDATED_AT TIMESTAMP NOT NULL COMMENT 'Last updated date',
    WALLET_ID VARCHAR(254) NOT NULL COMMENT 'Transaction reference to unique wallet identifier',
    OPERATION_ID VARCHAR(254) NOT NULL COMMENT 'Transaction reference to unique operation identifier',
    COMPLETED_ON TIMESTAMP NOT NULL COMMENT 'Transaction date',
    AMOUNT_VALUE NUMBER(10, 2) NOT NULL COMMENT 'Transaction amount',
    AMOUNT_CURRENCY VARCHAR(3) NOT NULL COMMENT 'Transaction currency',
    PRIMARY KEY (TRANSACTION_ID),
    FOREIGN KEY (WALLET_ID) REFERENCES WALLET(WALLET_ID),
    FOREIGN KEY (OPERATION_ID) REFERENCES OPERATION(OPERATION_ID)
);